# Generated by Django 6.0.6 on 2026-06-13 11:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('role', models.CharField(choices=[('visiteur', 'Visiteur'), ('client', 'Client'), ('bailleur', 'Bailleur'), ('agent', 'Agent'), ('manager', 'Manager')], default='client', max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent_affecte', models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_affectes', to=settings.AUTH_USER_MODEL, verbose_name='Agent affecté')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('type_bien', models.CharField(choices=[('terrain', 'Terrain'), ('batiment', 'Bâtiment'), ('appartement', 'Appartement'), ('villa', 'Villa'), ('commerce', 'Commerce')], max_length=20, verbose_name='Type de bien')),
                ('usage', models.CharField(choices=[('residence', 'Résidence'), ('bureau', 'Bureau'), ('commerce', 'Commerce'), ('agriculture', 'Agriculture')], max_length=20, verbose_name='Usage')),
                ('option', models.CharField(choices=[('location', 'Location'), ('vente', 'Vente')], max_length=10, verbose_name='Option')),
                ('zone_geographique', models.CharField(max_length=200, verbose_name='Zone géographique')),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Superficie (m²)')),
                ('prix', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Prix (FCFA)')),
                ('description', models.TextField(verbose_name='Description')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('publiee', 'Publiée'), ('retiree', 'Retirée'), ('refusee', 'Refusée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_agence', models.BooleanField(default=False, verbose_name="Annonce de l'agence")),
                ('agent_validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proprietes_validees', to=settings.AUTH_USER_MODEL, verbose_name='Agent validateur')),
                ('bailleur', models.ForeignKey(limit_choices_to={'role__in': ['bailleur', 'agent']}, on_delete=django.db.models.deletion.CASCADE, related_name='proprietes', to=settings.AUTH_USER_MODEL, verbose_name='Bailleur/Propriétaire')),
            ],
            options={
                'verbose_name': 'Propriété',
                'verbose_name_plural': 'Propriétés',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PhotoPropriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proprietes/', verbose_name='Image')),
                ('legende', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='immobilier.propriete')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='DemandeVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('date_souhaitee', models.DateField(blank=True, null=True, verbose_name='Date souhaitée')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_agent', models.TextField(blank=True, verbose_name="Commentaire de l'agent")),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visites_a_traiter', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_visite', to=settings.AUTH_USER_MODEL)),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_visite', to='immobilier.propriete')),
            ],
            options={
                'verbose_name': 'Demande de visite',
                'verbose_name_plural': 'Demandes de visite',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='immobilier.propriete')),
            ],
            options={
                'verbose_name': 'Favori',
                'unique_together': {('client', 'propriete')},
            },
        ),
    ]
